export const CONFIG = {
    API_URL: import.meta.env.VITE_API_URL || 'http://localhost:3000',
    DEFAULT_LANGUAGE: 'python',
    DEFAULT_THEME: 'system',
    DEFAULT_FONT_FAMILY: "'Consolas', 'Monaco', 'Courier New', monospace",
    DEFAULT_FONT_SIZE: 14,
    WARMUP_INTERVAL: 30000,
    MAX_ERROR_LINES: 20,
    MAX_ERROR_LENGTH: 500,
    IMAGE_STYLES: {
        maxWidth: '100%',
        height: 'auto',
        marginTop: '0.5rem',
        borderRadius: '4px'
    },
    DEFAULT_ERROR_COLOR: '#f44336',
    DEBUG_PATTERNS: [
        /^\[DEBUG\].*/i,
        /^DEBUG:.*/i,
        /^Checking source file:.*/i,
        /^Copying file to.*/i,
        /^Verifying copied file.*/i,
        /^File copy successful.*/i,
        /^Checking input file:.*/i
    ]
};

export const LANGUAGE_CONFIG = {
    modes: {
        python: 'python',
        javascript: 'javascript',
        java: 'java',
        cpp: 'c_cpp',
        c: 'c_cpp',
        rust: 'rust',
        php: 'php',
        r: 'r',
        ruby: 'ruby',
        csharp: 'csharp',
        kotlin: 'kotlin',
        go: 'golang',
        typescript: 'typescript',
        swift: 'swift',
        perl: 'perl',
        haskell: 'haskell',
        bash: 'sh'
    },
    templates: {
        python: 'print("Hello, World!")',
        javascript: 'console.log("Hello, World!");',
        java: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}',
        cpp: '#include <iostream>\n\nint main() {\n    std::cout << "Hello, World!" << std::endl;\n    return 0;\n}',
        c: '#include <stdio.h>\n\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}',
        rust: 'fn main() {\n    println!("Hello, World!");\n}',
        php: '<?php\n\necho "Hello, World!\\n";\n?>',
        r: 'print("Hello, World!\n")',
        ruby: 'puts "Hello, World!"',
        csharp: 'using System;\n\nclass Program\n{\n    static void Main(string[] args)\n    {\n        Console.WriteLine("Hello, World!");\n    }\n}',
        kotlin: 'fun main() {\n    println("Hello, World!")\n}',
        go: 'package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello, World!")\n}',
        typescript: 'console.log("Hello, World!");',
        swift: 'print("Hello, World!")',
        perl: 'print "Hello, World!\n";',
        haskell: 'main = putStrLn "Hello, World!"',
        bash: 'echo "Hello, World!"'
    },
    icons: {
        python: 'https://img.icons8.com/color/48/python.png',
        javascript: 'https://img.icons8.com/color/48/javascript.png',
        java: 'https://img.icons8.com/color/48/java-coffee-cup-logo.png',
        cpp: 'https://img.icons8.com/color/48/c-plus-plus-logo.png',
        c: 'https://img.icons8.com/color/48/c-programming.png',
        rust: 'https://img.icons8.com/color/48/rust.png',
        php: 'https://img.icons8.com/color/48/php.png',
        r: 'https://www.r-project.org/logo/Rlogo.png',
        ruby: 'https://img.icons8.com/color/48/ruby-programming-language.png',
        csharp: 'https://img.icons8.com/color/48/c-sharp-logo.png',
        kotlin: 'https://img.icons8.com/color/48/kotlin.png',
        go: 'https://img.icons8.com/color/48/golang.png',
        typescript: 'https://img.icons8.com/color/48/typescript.png',
        swift: 'https://img.icons8.com/color/48/swift.png',
        perl: 'https://img.icons8.com/color/48/perl.png',
        haskell: 'https://img.icons8.com/color/48/haskell.png',
        bash: 'https://img.icons8.com/color/48/bash.png'
    },
    names: {
        python: 'Python',
        javascript: 'JavaScript',
        java: 'Java',
        cpp: 'C++',
        c: 'C',
        rust: 'Rust',
        php: 'PHP',
        r: 'R',
        ruby: 'Ruby',
        csharp: 'C#',
        kotlin: 'Kotlin',
        go: 'Go',
        typescript: 'TypeScript',
        swift: 'Swift',
        perl: 'Perl',
        haskell: 'Haskell',
        bash: 'Bash'
    }
};

export const FONT_CONFIG = {
    families: {
        "'Consolas', 'Monaco', 'Courier New', monospace": 'Consolas',
        "'Courier New', Courier, monospace": 'Courier New',
        "'Monaco', 'Menlo', monospace": 'Monaco',
        "'Fira Code', 'Consolas', monospace": 'Fira Code',
        "'JetBrains Mono', 'Consolas', monospace": 'JetBrains Mono',
        "'Source Code Pro', 'Consolas', monospace": 'Source Code Pro',
        "'Roboto Mono', 'Consolas', monospace": 'Roboto Mono',
        'D2Coding, "D2Coding ligature", "Consolas", monospace': 'D2Coding',
        "'Inconsolata', 'Consolas', monospace": 'Inconsolata',
        "'Space Mono', 'Consolas', monospace": 'Space Mono',
        "'IBM Plex Mono', 'Consolas', monospace": 'IBM Plex Mono',
        "'Courier Prime', 'Courier New', monospace": 'Courier Prime',
        "'Red Hat Mono', 'Consolas', monospace": 'Red Hat Mono',
        "'PT Mono', 'Consolas', monospace": 'PT Mono',
        "'Cascadia Code', 'Consolas', monospace": 'Cascadia Code',
        "'Hack', 'Consolas', monospace": 'Hack',
        "'Victor Mono', 'Consolas', monospace": 'Victor Mono',
        "'Ubuntu Mono', 'Consolas', monospace": 'Ubuntu Mono',
        "'Anonymous Pro', 'Consolas', monospace": 'Anonymous Pro',
        "'Share Tech Mono', 'Consolas', monospace": 'Share Tech Mono',
        "'Oxygen Mono', 'Consolas', monospace": 'Oxygen Mono',
        "'Overpass Mono', 'Consolas', monospace": 'Overpass Mono',
        "'Nova Mono', 'Consolas', monospace": 'Nova Mono',
        "'Cousine', 'Consolas', monospace": 'Cousine',
        "'SF Mono', 'Monaco', 'Menlo', monospace": 'SF Mono',
        "'Menlo', 'Monaco', 'Consolas', monospace": 'Menlo',
        "'Liberation Mono', 'Courier New', monospace": 'Liberation Mono',
        "'DejaVu Sans Mono', 'Consolas', monospace": 'DejaVu Sans Mono'
    }
};

